knpu_oauth2_client:
  clients:
    # the key "facebook_main" can be anything, it
    # will create a service: "knpu.oauth2.client.facebook_main"
    portal_assos:
      # this will be one of the supported types
      type: generic
      provider_class: App\Provider\PortalProvider

      client_id: '44696575-2065-7374-2075-6e6971756521'
      client_secret: 'password'
      # the route that you're redirected to after
      # see the controller example below
      redirect_route: connect_portal_check
      redirect_params: {}