event_show:
  path: /
  controller: App\Controller\EventController::show

event_planner:
  path: /planner
  controller: App\Controller\EventController::planning

event_planner_user_list_json:
  path: /planner/users.json
  controller: App\Controller\PlannerController::userList

event_planner_user_task_json:
  path: /planner/tasks.json
  controller: App\Controller\PlannerController::userTaskList

# ----------
# EVENT RESOURCES
# ----------
event_resources:
  path: /resources
  controller: App\Controller\EventController::resources

event_resources_json:
  path: /resources.json
  controller: App\Controller\EventController::resourcesJson

event_resources_contact_json:
  path: /resources/{user_id}/contact.json
  controller: App\Controller\EventController::resourcesContact

event_resources_groups:
  path: /resources/requests/groups
  controller: App\Controller\EventController::resourcesEquityGroup

event_resources_groups_new:
  path: /resources/requests/groups/new
  controller: App\Controller\EventController::resourcesNewEquityGroup

event_resources_groups_edit:
  path: /resources/requests/groups/{group_id}/edit
  controller: App\Controller\EventController::resourcesEditEquityGroup

event_resources_groups_delete:
  path: /resources/requests/groups/{group_id}/delete
  controller: App\Controller\EventController::resourcesDeleteEquityGroup

event_resources_requests:
  path: /resources/requests
  controller: App\Controller\EventController::resourcesRequests

event_resources_requests_accept:
  path: /resources/requests/{user_id}/accept
  controller: App\Controller\EventController::resourcesRequestsAccept

event_resources_requests_refuse:
  path: /resources/requests/{user_id}/refuse
  controller: App\Controller\EventController::resourcesRequestsRefuse

event_resources_assos_members:
  path: /resources/orga_members.json
  controller: App\Controller\EventController::resourcesAsso

# ----------
# EVENT SETTINGS
# ----------
event_settings:
  path: /settings
  controller: App\Controller\EventController::edit

event_settings_access:
  path: /settings/access
  controller: App\Controller\EventController::access

# ----------
# EVENT TASK
# ----------
event_tasks:
  path: /tasks
  controller: App\Controller\TaskController:tasks

event_tasks_new:
  path: /tasks/new
  controller: App\Controller\TaskController:new

event_tasks_show:
  path: /tasks/{task_id}
  controller: App\Controller\TaskController:show

event_tasks_edit:
  path: /tasks/{task_id}/edit
  controller: App\Controller\TaskController:edit

event_tasks_delete:
  path: /tasks/{task_id}/delete
  controller: App\Controller\TaskController:delete

# ----------
# EVENT SKILLS
# ----------
event_skills:
  path: /skills
  controller: App\Controller\SkillController:index

event_skills_api_list:
  path: /skills.json
  controller: App\Controller\SkillController:apiList

event_skills_new:
  path: /skills/new
  controller: App\Controller\SkillController:new

event_skills_edit:
  path: /skills/{skill_id}/edit
  controller: App\Controller\SkillController:edit

event_skills_show:
  path: /skills/{skill_id}
  controller: App\Controller\SkillController:show

event_skills_delete:
  path: /skills/{skill_id}/delete
  controller: App\Controller\SkillController:delete
