event_new:
  path: /new
  controller: App\Controller\EventController::new

event_resources:
  path: /{id}/resources
  controller: App\Controller\EventController::resources

event_show:
  path: /{id}
  controller: App\Controller\EventController::show

event_settings:
  path: /{id}/settings
  controller: App\Controller\EventController::edit

event_settings_access:
  path: /settings/access
  controller: App\Controller\EventController::access

# ----------
# EVENT TASK
# ----------
event_tasks:
  path: /{id}/tasks
  controller: App\Controller\TaskController:tasks

event_tasks_new:
  path: /{id}/tasks/new
  controller: App\Controller\TaskController:new

event_tasks_show:
  path: /{id}/tasks/{task_id}
  controller: App\Controller\TaskController:show

event_tasks_edit:
  path: /{id}/tasks/{task_id}/edit
  controller: App\Controller\TaskController:edit

event_tasks_delete:
  path: /{id}/tasks/{task_id}/delete
  controller: App\Controller\TaskController:delete

# ----------
# EVENT SKILLS
# ----------
event_skills:
  path: /{id}/skills
  controller: App\Controller\SkillController:index

event_skills_api_list:
  path: /{id}/skills.json
  controller: App\Controller\SkillController:apiList

event_skills_new:
  path: /{id}/skills/new
  controller: App\Controller\SkillController:new

event_skills_edit:
  path: /{id}/skills/{skill_id}/edit
  controller: App\Controller\SkillController:edit

event_skills_show:
  path: /{id}/skills/{skill_id}
  controller: App\Controller\SkillController:show

event_skills_delete:
  path: /{id}/skills/{skill_id}/delete
  controller: App\Controller\SkillController:delete
