index:
    path: /
    controller: App\Controller\DefaultController::index

event:
    resource: "routes/events_manage.yaml"
    prefix: /events/{id}/manage

event_new:
    path: /events/new
    controller: App\Controller\EventController::new

landing:
    path: /landing
    controller: App\Controller\DefaultController::landing

timeline:
    path: /timeline
    controller: App\Controller\DefaultController::timeline

connect_portal_logout:
    path: /auth/logout
    controller: App\Controller\AuthenticationController:logout

connect_portal_connect:
    path: /auth/connect
    controller: App\Controller\AuthenticationController:connectAction

connect_portal_check:
    path: /auth/check
    controller: App\Controller\AuthenticationController:connectCheckAction