index:
    path: /
    controller: App\Controller\DefaultController::index

landing:
    path: /landing
    controller: App\Controller\DefaultController::landing

planning:
    path: /planning
    controller: App\Controller\DefaultController::planning

timeline:
    path: /timeline
    controller: App\Controller\DefaultController::timeline

event_new:
    path: /event/new
    controller: App\Controller\EventController::new

event_show:
    path: /event
    controller: App\Controller\EventController::show

event_resources:
    path: /event/resources
    controller: App\Controller\EventController::resources

event_settings:
    path: /event/settings
    controller: App\Controller\EventController::edit

event_settings_access:
    path: /event/settings/access
    controller: App\Controller\EventController::access

event_tasks:
    path: /event/tasks
    controller: App\Controller\TaskController:tasks


event_tasks_edit:
    path: /event/tasks/edit
    controller: App\Controller\TaskController:edit

connect_portal_connect:
    path: /auth/connect
    controller: App\Controller\AuthenticationController:connectAction

connect_portal_check:
    path: /auth/check
    controller: App\Controller\AuthenticationController:connectCheckAction