index:
    path: /
    controller: App\Controller\DefaultController::index

landing:
    path: /landing
    controller: App\Controller\DefaultController::landing

planning:
    path: /planning
    controller: App\Controller\DefaultController::planning

timeline:
    path: /timeline
    controller: App\Controller\DefaultController::timeline

event_new:
    path: /event/new
    controller: App\Controller\EventController::new

event_show:
    path: /event
    controller: App\Controller\EventController::show
