index:
    path: /
    controller: App\Controller\DefaultController::index

event:
    resource: "routes/events.yaml"
    prefix: /event

landing:
    path: /landing
    controller: App\Controller\DefaultController::landing

planning:
    path: /planning
    controller: App\Controller\DefaultController::planning

timeline:
    path: /timeline
    controller: App\Controller\DefaultController::timeline

connect_portal_connect:
    path: /auth/connect
    controller: App\Controller\AuthenticationController:connectAction

connect_portal_check:
    path: /auth/check
    controller: App\Controller\AuthenticationController:connectCheckAction